### ISSUE TITLE
createAuth0Client from @auth0/auth0-spa-js uses clientId instead of client_id

### ISSUE THREAD

**Issue by android-lewis** [spences10/sveltekit-with-auth0#173]
Seems that Auth0 SDK have moved to only accepting clientId in Auth0ClientOptions. Either they've deprecated client_id or it has another unstated purpose. 

Docs state to use clientId and that's what worked for me:

```javascript
    let auth0Client = await createAuth0Client({
    domain: config.domain,
    clientId: config.clientId,
  })
```

instead of;

```javascript
    let auth0Client = await createAuth0Client({
    domain: config.domain,
    client_id: config.clientId,
  })
```

**Comment by spences10** [comment]
Hey @android-lewis thanks for logging this issue!

This repo is in some serious need of work, I've not really done anything with it for over two years now 😅 

It's not using the latest auth0 package, so most stuff in here is more than likely incorrect if you are using it as a reference.

Sorry if you have been mislead in any way

**Comment by android-lewis** [comment]
Hey @spences10 thanks for getting back to me. 

No worries, I may update it myself with a few pull requests if I see anything else, as I'm working my way through implementing an Auth0 client in my pet Svelte project as I'm learning it 😀

**Comment by spences10** [comment]
Hey! That would be awesome and really appreciated if you do.

I’ll get round to doing it myself eventually if you don’t make any PRs but very happy if you do 😊
